networks:
  default:
    name: ros2-jazzy-network
    driver_opts:
      com.docker.network.bridge.name: br-ros2-jazzy

services:
  ros-jazzy:
    build:
      context: ./.devcontainer
    image: ros-jazzy
    # command: /bin/bash -c 'rm -f /tmp/rexlaunch.pgid && service ssh start && service rex docker-entrypoint'
    stdin_open: true
    container_name: ros-jazzy
    tty: true
    pid: "host"
    ipc: "host"
    init: true
    ports:
      - "2122:22"
    environment:
      - TZ=Europe/Warsaw
      - ROS_ENABLE_AUTOSTART=1
      - ROS_BUILD_ON_STARTUP=on-failure
      - ROS_ENABLE_CAN_BRIDGE=1
    volumes:
      - type: bind
        source: ./
        target: /home/rex/raptor_ws
        bind:
          create_host_path: true
      - type: bind
        source: ./.devcontainer/rex
        target: /etc/init.d/rex
        bind:
          create_host_path: true
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_healthy


  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./.devcontainer/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /var/opt/mosquitto/data:/mosquitto/data
      - /var/opt/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
