networks:
  default:
    name: ros-core-network
    driver_opts:
      com.docker.network.bridge.name: br-ros-core

services:
  ros-core:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: wisniax/ros-core:latest
    stdin_open: true
    container_name: ros-core
    hostname: ros-core
    tty: true
    pid: "host"
    ipc: "host"
    init: true
    ports:
      - "2122:22"
    environment:
      - TZ=Europe/Warsaw
      - ROS_ENABLE_AUTOSTART=1
      - ROS_BUILD_ON_STARTUP=on-failure
      - ROS_ENABLE_CAN_BRIDGE=1
    volumes:
      - type: bind
        source: ./
        target: /mnt/local
        bind:
          create_host_path: true
      - type: bind
        source: ./.devcontainer/rex
        target: /etc/init.d/rex
        bind:
          create_host_path: true
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./.devcontainer/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./.devcontainer/mosquitto_passwd:/mosquitto/mosquitto_passwd
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./.devcontainer/mqtt-server-certs:/mosquitto/certs
      - ./.devcontainer/mqtt-client-certs:/mosquitto/client-certs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "mosquitto", "-p", "8883", "-t", "$$SYS/#", "--cafile", "/mosquitto/client-certs/ca.crt", "-u", "raptors", "-P", "changeme", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
