log_dest file /mosquitto/log/mosquitto.log
password_file /mosquitto/mosquitto_passwd
listener 8883
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
