#Goal
ActuatorCommand[] commands

---
#Result
bool success
string error_reason


---
#SamplerFeedback
int32[] ids
float64[] current_position 
float64[] current_velocity 
float64[] current_effort
string state