<?xml version="1.0"?>
<package format="3">
  <name>mqtt_bridge</name>
  <version>0.2.0</version>
  <description>The mqtt_bridge package</description>

  <maintainer email="247733@edu.p.lodz.pl">Bartosz Mazurkiewicz</maintainer>
  <maintainer email="bartlomiejstasiak20@gmail.com">Bartłomiej Stasiak</maintainer>
  <author email="247733@edu.p.lodz.pl">Bartosz Mazurkiewicz</author>
  <license>MIT</license>

  <depend>rclcpp_components</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>rex_interfaces</depend>
  <depend>ament_index_cpp</depend>
  <depend>rcl_interfaces</depend>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <exec_depend>message_runtime</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>rcl_interfaces</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
