controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    clamp_position_controller:
      type: forward_command_controller/ForwardCommandController

    rotor_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    vacuum_rotor_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    brush_rotor_velocity_controller:
      type: forward_command_controller/ForwardCommandController
    
    velocity_command_controller:
      type: forward_command_controller/ForwardCommandController

velocity_command_controller:
  ros__parameters:
    joints:
      - platform_vel_joint
      - drill_vel_joint
      - container_vel_joint

    interface_name: velocity

position_controller:
  ros__parameters:
    joints:
      - platform_joint
      - drill_joint
      - container_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01

clamp_position_controller:
  ros__parameters:
    joints:
      - clamp_joint
    interface_name: position

rotor_velocity_controller:
  ros__parameters:
    joints:
      - rotor_joint

    interface_name: velocity


vacuum_rotor_velocity_controller:
  ros__parameters:
    joints:
      - vacuum_rotor_joint

    interface_name: velocity


brush_rotor_velocity_controller:
  ros__parameters:
    joints:
      - brush_rotor_joint

    interface_name: velocity