controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    platform_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    drill_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    rotor_velocity_controller:
      type: velocity_controllers/JointVelocityController


platform_controller:
  ros__parameters:
    joints:
      - platform_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

drill_position_controller:
  ros__parameters:
    joints:
      - drill_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

rotor_velocity_controller:
  ros__parameters:
    joint: 
      - rotor_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity