name: Build and publish Raptor Ros Core Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  [workflow_dispatch]
  tags:
  - 'v*.*.*' # Trigger on new tags like v1.0.0 (e.g., v1.0.0, v2.1.3)
jobs:

  build-and-publish-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f ./.devcontainer/Dockerfile -t wisniax/ros-core:latest .
    - name: Push the Docker image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push wisniax/ros-core:latest