name: Build image and run tests (soonTM).

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-amd64-only:
    runs-on: ubuntu-latest # x86-64 runner
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build AMD64 Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          platforms: linux/amd64
          push: false
          cache-from: type=registry,ref=wisniax/ros-core:buildcache-amd64