name: Build and publish Raptor Ros Core Docker Image

on:
  # push:
  #   branches: [ "master" ]
  #   tags: # This makes tags a filter for the push event.
  #     - 'v*.*.*' # Trigger on pushes that are also new tags like v1.0.0
  # pull_request:
  #   branches: [ "master" ]
  workflow_dispatch:
jobs:

  build-and-publish-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -f ./.devcontainer/Dockerfile -t wisniax/ros-core:latest .
    - name: Push the Docker image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push wisniax/ros-core:latest